### PR TITLE
chore(*): bump version to 0.2.0

### PR DESCRIPTION
**Pull request by erwinmombay**
bump version to 0.1.0

### CODE REVIEW

**Comment by SomeKittens** [comment]
Can you rebase this down to one commit?  (not sure what the deal is with the tests).

**Comment by erwinmombay** [comment]
squashed

**Comment by SomeKittens** [comment]
Tests are all failing on `Error: Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?`.

I'm getting these locally as well on master but not on master w/ Travis.  This leads me to believe that it's a versioning issue.  Mind checking that out?  Create a new issue if you think that's needed.

**Comment by erwinmombay** [comment]
got it. will check it out :clock1:

**Comment by SomeKittens** [comment]
(for clarity, I mean we've grabbed a newer version of a dependency that's breaking stuff, not the `0.2.0` version here.  Sorry for not being more clear earlier)

**Comment by erwinmombay** [comment]
@SomeKittens looks like its the latest jasmine-core 2.3.0. will figure out if its fixable on our end.

**Comment by erwinmombay** [comment]
fix for this can be found in https://github.com/angular/angular-hint/pull/80

**Comment by erwinmombay** [comment]
@SomeKittens this is green now! :dancer:

**Comment by erwinmombay** [comment]
fixed in https://github.com/angular/angular-hint/commit/05685a9961a3bce234b89af05c733f70428fa2cd

**Pull request closed without merging**
