### PR TITLE
feat(name scopes): Allow users to name scopes

### PR DESCRIPTION
**Pull request by SomeKittens**
Check for a `__ngHintName` property on scope/controllerAs value.  If found, name the scope that in the Scopes panel.

Fixes https://github.com/angular/batarang/issues/84

### CODE REVIEW

**Comment by likerRr** [comment]
Would be great to approve it as soon as possible. It's quite annoying to see such error in console

**Comment by SomeKittens** [comment]
@btford @erwinmombay

**Comment by erwinmombay** [comment]
landed as https://github.com/angular/angular-hint/commit/13107a574556bfc98852443787a710ca165276dd

**Comment by erwinmombay** [comment]
tested, LGTM. sorry for delay.

**Pull request closed without merging**
