### PR TITLE
fix(events): fix expression execution when expression has a semi colon

### PR DESCRIPTION
**Pull request by erwinmombay**
fix expression execution problem when expression has a semi colon.

### CODE REVIEW

**Comment by erwinmombay** [comment]
@SomeKittens @btford mind reviewing? Thanks.

**Comment by SomeKittens** [comment]
Looks good but I'd like a test covering the original case `ng-click="myFunc();"`

**Comment by erwinmombay** [comment]
@SomeKittens done.

**Comment by SomeKittens** [comment]
:+1:

**Comment by SomeKittens** [comment]
Landed in 5d73063f3fcc530ba2f4f2eeaeaaba7d58f874a7

**Pull request closed without merging**
