### PR TITLE
fix(scopes): don't break one time ngbind expressions

### PR DESCRIPTION
**Pull request by erwinmombay**

### CODE REVIEW

**Comment by SomeKittens** [comment]
Code LGTM, lemme pull that down and run tests locally since Travis is funky.

**Comment by SomeKittens** [comment]
Getting this failure with Karma
```
Chromium 44.0.2403 (Ubuntu 0.0.0) ngHintScopes scope.$watch should not run perf timers for one time bind expressions FAILED
	TypeError: Cannot read property 'eventType' of undefined
	    at Object.<anonymous> (/home/somekittens/Dropbox/angular/hint/test/scopes.spec.js:65:19)
```

**Comment by erwinmombay** [comment]
thanks for checking. will look into it and write some tests.

**Comment by SomeKittens** [comment]
Yep, update fixed tests.  Landed in 0b98cfacc62247b0ceed46c523385e588a55190d

**Pull request closed without merging**
